### ISSUE TITLE
Wrong url embedding from "Search for content" form  

### ISSUE THREAD

**Issue by insideth** [ColdTrick/embed_extended#10]
If you embed an image from this form, the inserted url is a temporal (session) one, for example: src="http://test.com/serve-file/e0/l1506173452/di/c1/B7d1eu9jHN_o9AWIaz1mNRDQDkYK6X_hwBSASlo6P70/1/38/icons/1585large.jpg"

So when you close session the image was lost.

**Comment by insideth** [comment]
Solved in #11

**Comment by oseg** [comment]
I suggest a simpler fix: https://github.com/oseg/embed_extended/commit/ab0f79d9ac8334f2c87d4968bb85c527d100dacd

**Comment by jdalsem** [comment]
Development on this plugin has stopped
