### ISSUE TITLE
Cannot embed files in Free HTML widget

### ISSUE THREAD

**Issue by oseg** [ColdTrick/embed_extended#16]
Context: elgg v2.3.7, widget_manager v8.3.1, widget_pack v1.3 & embed_extended v2.0.2

Scenario:
- log in as standard user
- create a group
- add a "file_to_embed" file in the group
- go to the group profile page
- add the "free HTML" widget
- customize the "free HTML" widget
- click on the "embed content" link
=> in the "Files" tab of the "Embed content" window, "no items found" is displayed

Expected result
=> The "file_to_embed" file should be displayed

However, if you want to embed the "file_to_embed" file in a page or in a comment, it is working as expected. The issue only happens in the "Free HTML" widget.

**Comment by jdalsem** [comment]
With latest versions i can not reproduce this specific issue
