### ISSUE TITLE
Wrong link to embedded pdf-, doc etc. -files

### ISSUE THREAD

**Issue by Pasley70** [ColdTrick/embed_extended#3]
If you embed a non viewable file like PDF oder DOC, you get the link:

http://domain.tld/123

instead of the "old" linked application-icon. Personally i like that you get the file title as link text! But the correct Link must be

http://domain.tld/file/view/123/file-name

**Comment by jdalsem** [comment]
Is that from the "normal" embed tab or from the "search" tab?

**Comment by Pasley70** [comment]
The "normal" emed tab. If i deactivate your plugin, i get the correct linked App-Icon instead.

**Comment by jdalsem** [comment]
Solved it. And thanks for reporting!
